### ISSUE TITLE
[BUG Report] v6.9(rc1.1) - Seen plugin is once again throwing a NoMethodError exception 

### ISSUE THREAD

**Issue by tayjaybabee** [Inspyre-Technologies/EveIRC#116]
**Describe the bug**
  * File: lib/seen.rb

**To Reproduce**
In a channel that the bot is in:
```irc
<Taylor> !seen dave
*no response
```

Console shows:

> [2019/08/27 20:56:00.853] !! /home/eve/EveIRC/lib/plugins/seen.rb:94:in `seen': undefined method `[]'
eClass (NoMethodError)
[2019/08/27 20:56:00.853] !!    /home/eve/EveIRC/lib/plugins/seen.rb:88:in `execute'
[2019/08/27 20:56:00.853] !!    /home/eve/.rvm/gems/ruby-2.6.1/gems/cinch-2.3.4/lib/cinch/plugin.rb:41
[2019/08/27 20:56:00.854] !!    /home/eve/.rvm/gems/ruby-2.6.1/gems/cinch-2.3.4/lib/cinch/plugin.rb:41
 levels) in __register_matchers'
[2019/08/27 20:56:00.854] !!    /home/eve/.rvm/gems/ruby-2.6.1/gems/cinch-2.3.4/lib/cinch/handler.rb:9
 call'

**Expected behavior**
The plugin is supposed to search a database file for the users name, the last thing they said, and when and where they said it and return it to the channel

#18 

PROPOSED SOLUTION: If someone else isn't willing to take a crack at this one I'll just deprecate the plugin and get a gem to do that job. ANy thoughts?

**Comment by tayjaybabee** [comment]
@doubledave You were looking into "struct" last night. I assume that had something to do with this issue? Let me know if there's something I can just quickly brief you on.

**Comment by doubledave** [comment]
@tayjaybabee Yes I was reading up on structs in Ruby last night to help me get an understanding on what is going on in this plugin to see what would be a good way to fix it.
